-- PostgreSQL container bootstrap is intentionally empty.
--
-- The custom image only provides the zhparser binary extension.
-- Flyway V1.1.3 creates the database-scoped zhparser extension,
-- public.zhparser_cfg, mappings, search_vector and its GIN index for
-- every database managed by the application.
--
-- Keeping database objects in Flyway makes fresh initialization and
-- logical backup restoration follow the same migration path.
