# application-dev.yaml、application-test.yaml
spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/devdata

blog:
  auth:
    refresh-cookie:
      secure: false
  jwt:
    access-ttl: 1d
  mail:
    enabled: false

logging:
  level:
    org.flywaydb: DEBUG
